# Generated by Django 4.1.4 on 2023-01-21 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='desc',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='person',
            name='time',
        ),
    ]
