# Generated by Django 4.1.4 on 2023-01-22 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_person_description_person_blood_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime.now),
        ),
    ]
