# Generated by Django 4.1.7 on 2023-04-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_person_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
