# Generated by Django 4.1.7 on 2023-04-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_person_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
